
[[install_jaeger]]
= Install AMP Streams on Openshift

The functionality of this quickstart depends on a running instance of the
https://access.redhat.com/products/red-hat-amq#streams[AMQ Streams] Operator. AMQ Streams is a Red Hat project based on Apache Kafka. To deploy AMQ Streams in the Openshift environment:

. Log in into the Openshift console as `kubeadmin` user (or any cluster administrator).
. Navigate to `Operators` -> `OperatorHub`.
. Search for `AMQ Streams` - click on the 'Red Hat Integration - AMQ Streams' operator (works with both community and Red Hat).
Install it with the default values.
. Run the following command to set up a Kafka cluster called `my-cluster` in your project (Note that this creates an OpenShift route, the name of which is calculated by the names of the project, cluster and OpenShift host. There is an upper limit for how long this name can be so these values are kept intentionally short. There are ways to allow longer names, which require settings beyond the scope of this quickstart):
+
[options="nowrap",subs="+attributes"]
----
$ oc apply -n {artifactId}-project -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
EOF
----
. Next set up a topic called `testing` in the `my-cluster` cluster we created:
+
[options="nowrap",subs="+attributes"]
----
oc apply -n microprofile-rm-kafka-project -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: testing
labels:
  strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
EOF
----