---
apiVersion: v1
kind: Service
metadata:
  name: microprofile-health-management
  labels:
    app.kubernetes.io/instance: microprofile-health
    app.kubernetes.io/name: microprofile-health
spec:
  ports:
    - name: management
      protocol: TCP
      port: 9990
      targetPort: 9990
  selector:
    app.kubernetes.io/instance: microprofile-health
    app.kubernetes.io/name: microprofile-health

