:rhosak-version: v1alpha1
// Keeping this file in the reactive messaging quickstart for now (rather than ../shared-doc
// since it will be quite application specific
[[install_rhosak]]
= Install RHOSAK on Openshift

The functionality of this quickstart depends on a running instance of the
https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-streams-for-apache-kafka[Red Hat OpenShift Streams for Apache Kafka (RHOSAK)] Operator. RHOSAK is a Red Hat managed cloud service based on Apache Kafka. It runs on OpenShift but outside your OpenShift environment.

== Setting up RHOSAK
We will summarize the steps required to set up a Kafka instance in RHOSAK here. They were correct at the time of writing and inspired by the following https://developers.redhat.com/developer-sandbox/activities/connecting-to-your-managed-kafka-instance[article] explaining how to set up an instance in the Developer Sandbox for Red Hat OpenShift, which allows you to try technologies on OpenShift for free. If these steps change, the RHOSAK documentation will have the up to date instructions. Finally, the steps below assume you are using the Developer Sandbox. If you are a paying customer of RHOSAK you should adjust the steps accordingly.

*Prerequisites:*
Create a https://developers.redhat.com/products/rhosak/getting-started[RHOSAK account] before doing the following steps:

1. From the https://developers.redhat.com/products/rhosak/getting-started[RHOSAK] console, create a Kafka instance. You need to specify a name for it Kafka instance, for example `my-quickstart-kafka`. In the rest of this text we will use `<kafka-name>` to represent `my-quickstart-kafka`. Apart from the name you can use default values for everything else. It will take a few minutes for your Kafka instance to be ready.
2. Go into the instance and create a topic called `testing`. Use the suggested defaults for everything else.
3. https://github.com/redhat-developer/app-services-cli[Download] the `rhosas` application for your OS. Make it available on your path.

== Configuring your application
The Quickstart was originally intended to run with local Kafka server. In order to configure it for RHOSAK, we will deploy a `ConfigMap` that provides the config properties required by MicroProfile Reactive Messaging based on the configuration of the Kafka instance.

[source]
----
# QS_HOME is your local folder containing this README
oc apply -f $QS_HOME/mp-rm-rhosak-properties.yml
----

If you look at the contents of the file you will see it follows the pattern of MicroProfile Config properties for Reactive Messaging. The ConfigMap properties are merged with the properties in the application's `miceroprofile-config.properties`. Where the same value exists in both places the ConfigMap entry takes so `mp.messaging.connector.smallrye-kafka.bootstrap.servers` from the ConfigMap value will be used. The ConfigMap also provides properties to set up authentication to the RHOSAK Kafka instance, and it contains references to properties (e.g. `${bootstrapServers}`) that will be populated from the service binding in the next step.

Once deployed this will store the ConfigMap settings in the application pod's `/etc/config/reactive-messaging-properties` directory.

## Connecting the application to Kafka

First we need to log in to RHOAS. The login process uses the browser session for the console.
----
rhoas login
----
Then we need to make `rhoas` use our Kafka instance
----
# Substitute <kafka-name> with the name of your Kafka instance
rhoas kafka use --name <kafka-name>
----
Then go to https://console.redhat.com/openshift/token and get the token to authenticate with your OpenShift cluster.

Execute
----
rhoas cluster connect --token {your token pasted here}
----
This will return some YAML which we will use in the next step. Behind the scenes this authenticates your OpenShift project to work with the RHOSAK Kafka instance, and creates objects containing the configuration to connect to Kafka. These were referenced by the `mp-rm-rhosak-properties.yml` we applied a moment ago.

We need to create a `ServiceBinding` to bind the `KafkaConnection` (that represents the Kafka instance) in our application.

To do so we create a service binding, with the YAML returned from the `rhoas cluster connect` command:

[source,yaml]
----
apiVersion: binding.operators.coreos.com/{rhosak-version}
kind: ServiceBinding
metadata:
  name: kafka-config
  namespace: <project-name>
spec:
  application:
    group: apps
    name: name-of-your-application
    resource: deployments
    version: v1

  bindAsFiles: true
  services:
  - group: rhoas.redhat.com
    version: v1alpha1
    kind: KafkaConnection
    name: <kafka-name>
----
In your actual returned YAML, the `<project-name>` and `<kafka-name>` placeholders will contain the correct values for your OpenShift project, and Kafka instance.

NOTE: You need to replace `name-of-your-application` with `reactive-messaging-qs`, which is the name we will use when creating the application later.

Save this adjusted output to `rhosak-binding.yaml`, and apply this service binding to your OpenShift cluster with:

[source]
----
oc apply -f ./rhosak-binding.yaml
----

When we deploy our application, this will create a config map bound to the `/bindings/rhosak-bindings` directory in the application pods.

The `extensions/initialize-server.cli` script will get run as part of initialising the application pod, and adds the mentioned `/bindings/rhosak-bindings` and `/etc/config/reactive-messaging-properties` folders as config sources in the `microprofile-config-smallrye` subsystem. This CLI script only gets added if we pass in the environment variable `QS_USE_RHOSAK=1` when starting the application.
