name: GLow CI Check Profiles
on:
  workflow_call:
    inputs:
      QUICKSTART_PATH:
        description: 'the path to the quickstart to test'
        required: true
        type: string
      PROFILES:
        description: 'Array of profiles to test. It is a simple string search looking for bootable-jar, openshift and provisioned-server'
        required: true
        type: string
      DEPLOYMENT_DIR:
        description: 'the path to the deployment dir, relative to QUICKSTART_PATH'
        required: false
        default: '.'
        type: string
jobs:
  openshift:
    name: Openshift ${{inputs.QUICKSTART_PATH}}
    if: ${{ contains(inputs.PROFILES, 'openshift') }}
    uses: ./.github/workflows/glow_ci_internal_tests.yml
    with:
      QUICKSTART_PATH: ${{inputs.QUICKSTART_PATH}}
      DEPLOYMENT_DIR: ${{inputs.DEPLOYMENT_DIR}}
      PROFILE: 'openshift'
  provisioned-server:
    name: Provisioned Server ${{inputs.QUICKSTART_PATH}}
    if: ${{ contains(inputs.PROFILES, 'provisioned-server') }}
    uses: ./.github/workflows/glow_ci_internal_tests.yml
    with:
      QUICKSTART_PATH: ${{inputs.QUICKSTART_PATH}}
      DEPLOYMENT_DIR: ${{inputs.DEPLOYMENT_DIR}}
      PROFILE: 'provisioned-server'
  # Skip bootable jar until the plugin implements GLow support for bootable jar
  bootable-jar:
    name: Openshift ${{inputs.QUICKSTART_PATH}}
    if: ${{ contains(inputs.PROFILES, 'bootable-jar') }}
    uses: ./.github/workflows/glow_ci_internal_tests.yml
    with:
      QUICKSTART_PATH: ${{inputs.QUICKSTART_PATH}}
      DEPLOYMENT_DIR: ${{inputs.DEPLOYMENT_DIR}}
      PROFILE: 'bootable-jar'
