name: WildFly Glow CI

on:
  push:
    branches:
      - port-to-glow

env:
  WILDFLY_VERSION: 30.0.0.Final

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  wildfly-maven:
    # Pre-populate the maven repo with the WildFly Maven artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: wildfly-glow-ci-wildfly-${{ env.WILDFLY_VERSION }}
      - name: WildFly EE Feature Pack
        run: mvn -B dependency:get -Dartifact=org.wildfly:wildfly-ee-feature-pack-galleon-shared:${WILDFLY_VERSION}:pom
      - name: WildFly Galleon Pack
        run: mvn -B dependency:get -Dartifact=org.wildfly:wildfly-feature-pack-galleon-shared:${WILDFLY_VERSION}:pom
      - name: Archive the repository
        run:  |
          cd ~
          find ./.m2/repository -type d -name "*Final" -print0 | xargs -0 tar -czf ~/wildfly-maven-repository.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: wildfly-maven-repository
          path: ~/wildfly-maven-repository.tar.gz
          retention-days: 1

  batch-processing:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: batch-processing
      PROFILES: 'provisioned-server, openshift'
  bmt:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: bmt
      PROFILES: 'provisioned-server, openshift'
  cmt:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: cmt
      PROFILES: 'provisioned-server, openshift'
  ee-security:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: ee-security
      PROFILES: 'provisioned-server, openshift'
  ejb-remote:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: ejb-remote
      PROFILES: 'provisioned-server, openshift'
  ejb-security-context-propagation:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: ejb-security-context-propagation
      # Not set up for OpenShift
      PROFILES: 'provisioned-server'
  helloworld-mdb:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: helloworld-mdb
      PROFILES: 'provisioned-server, openshift'
  helloworld:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: helloworld
      PROFILES: 'provisioned-server, openshift'
  http-custom-mechanism:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: http-custom-mechanism
      PROFILES: 'provisioned-server'
      DEPLOYMENT_DIR: webapp
  jsonp:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: jsonp
      PROFILES: 'provisioned-server, openshift'
  # This does not use any of the profiles at the moment
  #  jta-crach-rec:
  #    needs: wildfly-maven
  #    uses: ./.github/workflows/glow_ci_internal.yml
  #    with:
  #      QUICKSTART_PATH: jta-crach-rec
  #      PROFILES: 'provisioned-server, openshift'
  kitchensink:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: kitchensink
      PROFILES: 'provisioned-server, openshift'
  microprofile-config:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: microprofile-config
      PROFILES: 'bootable-jar, openshift'
  microprofile-health:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: microprofile-health
      PROFILES: 'bootable-jar, openshift'
  microprofile-jwt:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: microprofile-jwt
      PROFILES: 'bootable-jar, openshift'
  microprofile-openapi:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: microprofile-openapi
      PROFILES: 'bootable-jar, openshift'
  microprofile-reactive-messaging-kafka:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: microprofile-reactive-messaging-kafka
      PROFILES: 'bootable-jar, openshift'
  numberguess:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: numberguess
      PROFILES: 'provisioned-server, openshift'
  remote-helloworld-mdb:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: remote-helloworld-mdb
      PROFILES: 'provisioned-server, openshift'
  # TODO spring-resteasy-is not properly incorporated with Galleon yet
  spring-resteasy:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: spring-resteasy
      PROFILES: 'provisioned-server, openshift'
  temperature-converter:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: temperature-converter
      PROFILES: 'provisioned-server, openshift'
  thread-racing:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: thread-racing
      PROFILES: 'provisioned-server, openshift'
  websocket-hello:
    needs: wildfly-maven
    uses: ./.github/workflows/glow_ci_internal.yml
    with:
      QUICKSTART_PATH: websocket-hello
      PROFILES: 'provisioned-server, openshift'
